# =========================== Basic Settings ===========================
# machine info
num_gpus_per_job: 4  # number of gpus each job need
num_cpus_per_job: 63  # number of cpus each job need
memory_per_job: 380  # memory requirement each job need
gpu_type: "nvidia-tesla-p100"

# data
dataset: imagenet1k
data_transforms: imagenet1k_basic
data_loader: imagenet1k_basic
dataset_dir: data/imagenet
data_loader_workers: 62

# info
num_classes: 1000
image_size: 224
topk: [1, 5]
num_epochs: 100

# optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nesterov: True

# lr
lr: 0.1
lr_scheduler: multistep
multistep_lr_milestones: [30, 60, 90]
multistep_lr_gamma: 0.1

# model profiling
profiling: [gpu]

# pretrain, resume, test_only
pretrained: ''
resume: ''
test_only: False

#
random_seed: 1995
batch_size: 256
model: ''
reset_parameters: True


# =========================== Override Settings ===========================
log_dir: logs/
slimmable_training: True
model: models.autoslim_mnasnet
width_mult_list: [1, 2, 3]
channel_num_list:
  - [16, 8, 24, 16, 48, 16, 24, 16, 48, 32, 48, 32, 48, 32, 192, 56, 400, 56, 400, 56, 400, 80, 432, 80, 648, 192, 864, 192, 864, 192, 864, 192, 1728, 280, 1280, 1000]  # 217M, divisor12
  - [16, 8, 40, 24, 48, 24, 40, 24, 48, 40, 80, 40, 48, 40, 352, 64, 400, 64, 400, 64, 464, 80, 432, 80, 792, 288, 864, 288, 864, 288, 1008, 288, 1728, 360, 1920, 1000]  # 315M, divisor12
  - [16, 8, 64, 32, 56, 32, 72, 32, 104, 64, 128, 64, 96, 64, 384, 104, 528, 104, 464, 104, 720, 128, 576, 128, 864, 288, 1584, 288, 1728, 288, 1728, 288, 1728, 480, 1920, 1000]  # 539M, divisor12
data_transforms: imagenet1k_mobile
# num_gpus_per_job:
# lr:
# lr_scheduler:
# exp_decaying_lr_gamma:
# num_epochs:
# batch_size:
# test pretrained
test_only: True
pretrained: logs/autoslim_mnasnet.pt
